import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Lato({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-primary-100'}>
        <nav className="p-4 bg-primary-800  text-white flex">
          <ul className="flex gap-3 w-full items-center">
            <li className="font-bold text-xl px-1 font-serif italic text-primary-600 bg-white border rounded-lg list-none">
              SS
            </li>
            <li className="hover:text-primary-500 list-none">
              <Link href="/">Expenses</Link>
            </li>
            <li className="hover:text-primary-500 list-none">
              <Link href="/wallets">Wallets</Link>
            </li>
            <li className="text-transparent hover:text-primary-50  list-none ml-auto">
              <Link href="/insights">Insights</Link>
            </li>
          </ul>
        </nav>
        <div className="w-full flex justify-center">{children}</div>
      </body>
    </html>
  );
}
