version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'spend-smart'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=spend-smart
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always